linters:
  enable:
    - govet
    - revive
    - staticcheck
    - lll
    - misspell
    - dupword
  disable:
    - gosimple
    - unused
    - errcheck

linters-settings:
  lll:
    line-length: 90

issues:
  exclude-rules:
    - text: unused-parameter
      linters:
        - revive
